name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test ./...

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build event-api image
        run: docker build --build-arg APP=event-api -t project-notification/event-api .

      - name: Build kafka-consumer image
        run: docker build --build-arg APP=kafka-consumer -t project-notification/kafka-consumer .
